set beautifierrules C:\repo\risk\rules.br
beautify C:\repo\risk\source\database\modules\flj\package_specs\k_flujo.spc
beautify C:\repo\risk\source\database\modules\flj\package_specs\k_flujo_util.spc
beautify C:\repo\risk\source\database\modules\flj\package_specs\t_flujos_api.spc
beautify C:\repo\risk\source\database\modules\flj\package_specs\t_flujo_instancias_api.spc
beautify C:\repo\risk\source\database\modules\flj\package_specs\t_flujo_instancia_aprobaciones_api.spc
beautify C:\repo\risk\source\database\modules\flj\package_specs\t_flujo_instancia_historial_api.spc
beautify C:\repo\risk\source\database\modules\flj\package_specs\t_flujo_instancia_pasos_api.spc
beautify C:\repo\risk\source\database\modules\flj\package_specs\t_flujo_pasos_api.spc
beautify C:\repo\risk\source\database\modules\flj\package_specs\t_flujo_transiciones_api.spc
beautify C:\repo\risk\source\database\modules\glo\package_specs\k_servicio_glo.spc
beautify C:\repo\risk\source\database\modules\glo\package_specs\t_barrios_api.spc
beautify C:\repo\risk\source\database\modules\glo\package_specs\t_ciudades_api.spc
beautify C:\repo\risk\source\database\modules\glo\package_specs\t_departamentos_api.spc
beautify C:\repo\risk\source\database\modules\glo\package_specs\t_distritos_api.spc
beautify C:\repo\risk\source\database\modules\glo\package_specs\t_idiomas_api.spc
beautify C:\repo\risk\source\database\modules\glo\package_specs\t_monedas_api.spc
beautify C:\repo\risk\source\database\modules\glo\package_specs\t_paises_api.spc
beautify C:\repo\risk\source\database\modules\msj\package_specs\k_mensajeria.spc
beautify C:\repo\risk\source\database\modules\msj\package_specs\k_servicio_msj.spc
beautify C:\repo\risk\source\database\modules\msj\package_specs\t_correos_api.spc
beautify C:\repo\risk\source\database\modules\msj\package_specs\t_correo_adjuntos_api.spc
beautify C:\repo\risk\source\database\modules\msj\package_specs\t_correo_plantillas_api.spc
beautify C:\repo\risk\source\database\modules\msj\package_specs\t_dispositivo_suscripciones_api.spc
beautify C:\repo\risk\source\database\modules\msj\package_specs\t_mensajeria_categorias_api.spc
beautify C:\repo\risk\source\database\modules\msj\package_specs\t_mensajes_api.spc
beautify C:\repo\risk\source\database\modules\msj\package_specs\t_mensajes_recibidos_api.spc
beautify C:\repo\risk\source\database\modules\msj\package_specs\t_mensaje_plantillas_api.spc
beautify C:\repo\risk\source\database\modules\msj\package_specs\t_notificaciones_api.spc
beautify C:\repo\risk\source\database\modules\msj\package_specs\t_notificacion_plantillas_api.spc
beautify C:\repo\risk\source\database\modules\msj\package_specs\t_usuario_suscripciones_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_aplicacion.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_aplicacion_util.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_archivo.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_async.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_auditoria.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_autenticacion.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_autorizacion.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_cadena.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_clave.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_contexto.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_crypto.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_dato.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_dispositivo.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_dominio.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_entidad.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_error.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_error_util.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_html.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_importacion.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_json_util.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_lob_util.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_modulo.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_modulo_util.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_monitoreo.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_monitoreo_aut.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_objeto_util.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_operacion.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_operacion_util.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_parametro.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_parametro_util.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_reporte.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_reporte_gen.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_servicio.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_servicio_aut.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_servicio_gen.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_sesion.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_significado.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_significado_util.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_sistema.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_trabajo.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_usuario.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_util.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_aplicaciones_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_aplicacion_parametros_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_archivos_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_archivos_hist_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_archivo_definiciones_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_autenticacion_origenes_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_autenticacion_tipos_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_datos_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_dato_definiciones_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_dispositivos_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_dispositivo_ubicaciones_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_documento_tipos_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_dominios_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_entidades_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_entidad_roles_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_entidad_usuarios_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_errores_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_importaciones_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_importacion_parametros_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_migraciones_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_modulos_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_monitoreos_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_monitoreo_ejecuciones_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_operaciones_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_operacion_logs_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_operacion_parametros_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_parametros_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_parametro_definiciones_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_permisos_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_personas_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_reportes_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_roles_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_rol_permisos_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_rol_usuarios_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_servicios_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_sesiones_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_significados_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_significado_dominios_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_trabajos_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_usuarios_api.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\t_usuario_claves_api.spc
beautify C:\repo\risk\test\database\package_specs\test_gb_personas.spc
beautify C:\repo\risk\test\database\package_specs\test_k_aplicacion.spc
beautify C:\repo\risk\test\database\package_specs\test_k_archivo.spc
beautify C:\repo\risk\test\database\package_specs\test_k_auditoria.spc
beautify C:\repo\risk\test\database\package_specs\test_k_autenticacion.spc
beautify C:\repo\risk\test\database\package_specs\test_k_autorizacion.spc
beautify C:\repo\risk\test\database\package_specs\test_k_cadena.spc
beautify C:\repo\risk\test\database\package_specs\test_k_clave.spc
beautify C:\repo\risk\test\database\package_specs\test_k_contexto.spc
beautify C:\repo\risk\test\database\package_specs\test_k_dato.spc
beautify C:\repo\risk\test\database\package_specs\test_k_dispositivo.spc
beautify C:\repo\risk\test\database\package_specs\test_k_dominio.spc
beautify C:\repo\risk\test\database\package_specs\test_k_error.spc
beautify C:\repo\risk\test\database\package_specs\test_k_html.spc
beautify C:\repo\risk\test\database\package_specs\test_k_importacion.spc
beautify C:\repo\risk\test\database\package_specs\test_k_mensajeria.spc
beautify C:\repo\risk\test\database\package_specs\test_k_modulo.spc
beautify C:\repo\risk\test\database\package_specs\test_k_objeto_util.spc
beautify C:\repo\risk\test\database\package_specs\test_k_operacion.spc
beautify C:\repo\risk\test\database\package_specs\test_k_reporte.spc
beautify C:\repo\risk\test\database\package_specs\test_k_servicio.spc
beautify C:\repo\risk\test\database\package_specs\test_k_sesion.spc
beautify C:\repo\risk\test\database\package_specs\test_k_significado.spc
beautify C:\repo\risk\test\database\package_specs\test_k_sistema.spc
beautify C:\repo\risk\test\database\package_specs\test_k_trabajo.spc
beautify C:\repo\risk\test\database\package_specs\test_k_usuario.spc
beautify C:\repo\risk\test\database\package_specs\test_k_util.spc
beautify C:\repo\risk\test\database\package_specs\test_ora_codecop.spc
beautify C:\repo\risk\test\database\package_specs\test_y_dato.spc
beautify C:\repo\risk\test\database\package_specs\test_y_respuesta.spc
beautify C:\repo\risk\source\database\modules\flj\package_bodies\k_flujo.bdy
beautify C:\repo\risk\source\database\modules\flj\package_bodies\k_flujo_util.bdy
beautify C:\repo\risk\source\database\modules\flj\package_bodies\t_flujos_api.bdy
beautify C:\repo\risk\source\database\modules\flj\package_bodies\t_flujo_instancias_api.bdy
beautify C:\repo\risk\source\database\modules\flj\package_bodies\t_flujo_instancia_aprobaciones_api.bdy
beautify C:\repo\risk\source\database\modules\flj\package_bodies\t_flujo_instancia_historial_api.bdy
beautify C:\repo\risk\source\database\modules\flj\package_bodies\t_flujo_instancia_pasos_api.bdy
beautify C:\repo\risk\source\database\modules\flj\package_bodies\t_flujo_pasos_api.bdy
beautify C:\repo\risk\source\database\modules\flj\package_bodies\t_flujo_transiciones_api.bdy
beautify C:\repo\risk\source\database\modules\glo\package_bodies\k_servicio_glo.bdy
beautify C:\repo\risk\source\database\modules\glo\package_bodies\t_barrios_api.bdy
beautify C:\repo\risk\source\database\modules\glo\package_bodies\t_ciudades_api.bdy
beautify C:\repo\risk\source\database\modules\glo\package_bodies\t_departamentos_api.bdy
beautify C:\repo\risk\source\database\modules\glo\package_bodies\t_distritos_api.bdy
beautify C:\repo\risk\source\database\modules\glo\package_bodies\t_idiomas_api.bdy
beautify C:\repo\risk\source\database\modules\glo\package_bodies\t_monedas_api.bdy
beautify C:\repo\risk\source\database\modules\glo\package_bodies\t_paises_api.bdy
beautify C:\repo\risk\source\database\modules\msj\package_bodies\k_mensajeria.bdy
beautify C:\repo\risk\source\database\modules\msj\package_bodies\k_servicio_msj.bdy
beautify C:\repo\risk\source\database\modules\msj\package_bodies\t_correos_api.bdy
beautify C:\repo\risk\source\database\modules\msj\package_bodies\t_correo_adjuntos_api.bdy
beautify C:\repo\risk\source\database\modules\msj\package_bodies\t_correo_plantillas_api.bdy
beautify C:\repo\risk\source\database\modules\msj\package_bodies\t_dispositivo_suscripciones_api.bdy
beautify C:\repo\risk\source\database\modules\msj\package_bodies\t_mensajeria_categorias_api.bdy
beautify C:\repo\risk\source\database\modules\msj\package_bodies\t_mensajes_api.bdy
beautify C:\repo\risk\source\database\modules\msj\package_bodies\t_mensajes_recibidos_api.bdy
beautify C:\repo\risk\source\database\modules\msj\package_bodies\t_mensaje_plantillas_api.bdy
beautify C:\repo\risk\source\database\modules\msj\package_bodies\t_notificaciones_api.bdy
beautify C:\repo\risk\source\database\modules\msj\package_bodies\t_notificacion_plantillas_api.bdy
beautify C:\repo\risk\source\database\modules\msj\package_bodies\t_usuario_suscripciones_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_aplicacion.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_aplicacion_util.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_archivo.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_async.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_auditoria.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_autenticacion.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_autorizacion.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_cadena.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_clave.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_contexto.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_crypto.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_dato.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_dispositivo.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_dominio.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_entidad.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_error.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_error_util.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_html.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_importacion.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_json_util.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_lob_util.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_modulo.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_modulo_util.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_monitoreo.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_monitoreo_aut.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_objeto_util.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_operacion.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_operacion_util.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_parametro.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_parametro_util.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_reporte.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_reporte_gen.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_servicio.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_servicio_aut.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_servicio_gen.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_sesion.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_significado.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_significado_util.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_sistema.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_trabajo.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_usuario.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_util.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_aplicaciones_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_aplicacion_parametros_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_archivos_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_archivos_hist_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_archivo_definiciones_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_autenticacion_origenes_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_autenticacion_tipos_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_datos_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_dato_definiciones_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_dispositivos_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_dispositivo_ubicaciones_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_documento_tipos_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_dominios_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_entidades_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_entidad_roles_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_entidad_usuarios_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_errores_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_importaciones_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_importacion_parametros_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_migraciones_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_modulos_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_monitoreos_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_monitoreo_ejecuciones_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_operaciones_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_operacion_logs_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_operacion_parametros_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_parametros_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_parametro_definiciones_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_permisos_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_personas_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_reportes_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_roles_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_rol_permisos_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_rol_usuarios_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_servicios_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_sesiones_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_significados_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_significado_dominios_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_trabajos_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_usuarios_api.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\t_usuario_claves_api.bdy
beautify C:\repo\risk\test\database\package_bodies\test_gb_personas.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_aplicacion.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_archivo.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_auditoria.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_autenticacion.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_autorizacion.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_cadena.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_clave.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_contexto.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_dato.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_dispositivo.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_dominio.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_error.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_html.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_importacion.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_mensajeria.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_modulo.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_objeto_util.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_operacion.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_reporte.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_servicio.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_sesion.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_significado.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_sistema.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_trabajo.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_usuario.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_util.bdy
beautify C:\repo\risk\test\database\package_bodies\test_ora_codecop.bdy
beautify C:\repo\risk\test\database\package_bodies\test_y_dato.bdy
beautify C:\repo\risk\test\database\package_bodies\test_y_respuesta.bdy
beautify C:\repo\risk\source\database\modules\risk\functions\f_procesar_reporte.fnc
beautify C:\repo\risk\source\database\modules\risk\functions\f_procesar_servicio.fnc
beautify C:\repo\risk\source\database\modules\risk\procedures\p_configurar_modificacion.prc
beautify C:\repo\risk\source\database\modules\risk\procedures\p_control_auditoria.prc
beautify C:\repo\risk\source\database\modules\flj\triggers\ga_flujos.trg
beautify C:\repo\risk\source\database\modules\flj\triggers\ga_flujo_instancias.trg
beautify C:\repo\risk\source\database\modules\flj\triggers\ga_flujo_instancia_aprobaciones.trg
beautify C:\repo\risk\source\database\modules\flj\triggers\ga_flujo_instancia_historial.trg
beautify C:\repo\risk\source\database\modules\flj\triggers\ga_flujo_instancia_pasos.trg
beautify C:\repo\risk\source\database\modules\flj\triggers\ga_flujo_pasos.trg
beautify C:\repo\risk\source\database\modules\flj\triggers\ga_flujo_transiciones.trg
beautify C:\repo\risk\source\database\modules\flj\triggers\gb_flujo_instancia_pasos.trg
beautify C:\repo\risk\source\database\modules\flj\triggers\gb_roles.trg
beautify C:\repo\risk\source\database\modules\flj\triggers\t_flujos_ioiud.trg
beautify C:\repo\risk\source\database\modules\flj\triggers\t_flujo_instancias_ioiud.trg
beautify C:\repo\risk\source\database\modules\flj\triggers\t_flujo_instancia_aprobaciones_ioiud.trg
beautify C:\repo\risk\source\database\modules\flj\triggers\t_flujo_instancia_historial_ioiud.trg
beautify C:\repo\risk\source\database\modules\flj\triggers\t_flujo_instancia_pasos_ioiud.trg
beautify C:\repo\risk\source\database\modules\flj\triggers\t_flujo_pasos_ioiud.trg
beautify C:\repo\risk\source\database\modules\flj\triggers\t_flujo_transiciones_ioiud.trg
beautify C:\repo\risk\source\database\modules\glo\triggers\ga_barrios.trg
beautify C:\repo\risk\source\database\modules\glo\triggers\ga_ciudades.trg
beautify C:\repo\risk\source\database\modules\glo\triggers\ga_departamentos.trg
beautify C:\repo\risk\source\database\modules\glo\triggers\ga_distritos.trg
beautify C:\repo\risk\source\database\modules\glo\triggers\ga_idiomas.trg
beautify C:\repo\risk\source\database\modules\glo\triggers\ga_monedas.trg
beautify C:\repo\risk\source\database\modules\glo\triggers\ga_paises.trg
beautify C:\repo\risk\source\database\modules\glo\triggers\t_barrios_ioiud.trg
beautify C:\repo\risk\source\database\modules\glo\triggers\t_ciudades_ioiud.trg
beautify C:\repo\risk\source\database\modules\glo\triggers\t_departamentos_ioiud.trg
beautify C:\repo\risk\source\database\modules\glo\triggers\t_idiomas_ioiud.trg
beautify C:\repo\risk\source\database\modules\glo\triggers\t_monedas_ioiud.trg
beautify C:\repo\risk\source\database\modules\glo\triggers\t_paises_ioiud.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\ga_correos.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\ga_correo_adjuntos.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\ga_correo_plantillas.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\ga_dispositivo_suscripciones.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\ga_mensajeria_categorias.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\ga_mensajes.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\ga_mensajes_recibidos.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\ga_mensaje_plantillas.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\ga_notificaciones.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\ga_notificacion_plantillas.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\ga_usuario_suscripciones.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\gb_mensajes.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\t_correos_ioiud.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\t_correo_adjuntos_ioiud.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\t_correo_plantillas_ioiud.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\t_dispositivo_suscripciones_ioiud.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\t_mensajeria_categorias_ioiud.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\t_mensajes_ioiud.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\t_mensajes_recibidos_ioiud.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\t_mensaje_plantillas_ioiud.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\t_notificaciones_ioiud.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\t_notificacion_plantillas_ioiud.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\t_usuario_suscripciones_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_aplicaciones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_aplicacion_parametros.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_archivos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_archivos_hist.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_archivo_definiciones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_autenticacion_origenes.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_autenticacion_tipos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_datos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_dato_definiciones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_dispositivos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_dispositivo_ubicaciones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_documento_tipos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_dominios.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_entidades.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_entidad_roles.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_entidad_usuarios.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_errores.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_importaciones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_importacion_parametros.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_migraciones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_modulos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_monitoreos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_monitoreo_ejecuciones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_operaciones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_operacion_logs.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_operacion_parametros.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_parametros.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_parametro_definiciones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_permisos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_personas.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_reportes.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_roles.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_rol_permisos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_rol_usuarios.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_servicios.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_sesiones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_significados.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_significado_dominios.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_trabajos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_usuarios.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\ga_usuario_claves.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_archivos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_datos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_dato_definiciones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_entidades.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_errores_actualizar_clave.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_operaciones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_operacion_parametros.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_personas.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_reportes.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_servicios.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_sesiones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_trabajos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_usuarios.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gf_archivos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gf_operaciones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_aplicaciones_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_aplicacion_parametros_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_archivos_hist_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_archivos_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_archivo_definiciones_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_autenticacion_origenes_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_autenticacion_tipos_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_datos_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_dato_definiciones_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_dispositivos_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_dispositivo_ubicaciones_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_documento_tipos_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_dominios_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_entidades_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_entidad_roles_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_entidad_usuarios_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_errores_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_importaciones_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_importacion_parametros_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_migraciones_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_modulos_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_monitoreos_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_monitoreo_ejecuciones_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_operaciones_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_operacion_logs_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_operacion_parametros_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_parametros_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_parametro_definiciones_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_permisos_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_personas_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_reportes_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_roles_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_rol_permisos_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_rol_usuarios_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_servicios_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_sesiones_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_significados_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_significado_dominios_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_trabajos_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_usuarios_ioiud.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\t_usuario_claves_ioiud.trg
beautify C:\repo\risk\source\database\dependencies\occ\ddl\type\integer_c.tps
beautify C:\repo\risk\source\database\dependencies\occ\ddl\type\rule_result_c.tps
beautify C:\repo\risk\source\database\dependencies\occ\ddl\type\rule_result_o.tps
beautify C:\repo\risk\source\database\dependencies\occ\ddl\type\string_c.tps
beautify C:\repo\risk\source\database\dependencies\occ\ddl\type\verification_result_c.tps
beautify C:\repo\risk\source\database\dependencies\occ\ddl\type\verification_result_o.tps
beautify C:\repo\risk\source\database\modules\glo\type_specs\y_barrio.tps
beautify C:\repo\risk\source\database\modules\glo\type_specs\y_ciudad.tps
beautify C:\repo\risk\source\database\modules\glo\type_specs\y_departamento.tps
beautify C:\repo\risk\source\database\modules\glo\type_specs\y_distrito.tps
beautify C:\repo\risk\source\database\modules\glo\type_specs\y_pais.tps
beautify C:\repo\risk\source\database\modules\msj\type_specs\y_correo.tps
beautify C:\repo\risk\source\database\modules\msj\type_specs\y_mensaje.tps
beautify C:\repo\risk\source\database\modules\msj\type_specs\y_notificacion.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_archivo.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_cadenas.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_dato.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_datos.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_dispositivo.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_error.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_lista.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_lista_parametros.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_objeto.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_objetos.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_pagina.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_pagina_parametros.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_parametro.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_parametros.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_permiso.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_permisos.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_plantilla.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_respuesta.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_rol.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_sesion.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_significado.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_tipo_atributo.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_tipo_atributos.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_usuario.tps
beautify C:\repo\risk\source\database\dependencies\occ\ddl\type\rule_result_o.tpb
beautify C:\repo\risk\source\database\modules\glo\type_bodies\y_barrio.tpb
beautify C:\repo\risk\source\database\modules\glo\type_bodies\y_ciudad.tpb
beautify C:\repo\risk\source\database\modules\glo\type_bodies\y_departamento.tpb
beautify C:\repo\risk\source\database\modules\glo\type_bodies\y_distrito.tpb
beautify C:\repo\risk\source\database\modules\glo\type_bodies\y_pais.tpb
beautify C:\repo\risk\source\database\modules\msj\type_bodies\y_correo.tpb
beautify C:\repo\risk\source\database\modules\msj\type_bodies\y_mensaje.tpb
beautify C:\repo\risk\source\database\modules\msj\type_bodies\y_notificacion.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_archivo.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_dato.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_dispositivo.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_error.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_lista.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_lista_parametros.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_pagina.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_pagina_parametros.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_parametro.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_permiso.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_plantilla.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_respuesta.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_rol.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_sesion.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_significado.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_tipo_atributo.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_usuario.tpb
exit application
