set beautifierrules C:\repo\risk\rules.br
beautify C:\repo\risk\source\database\modules\flj\package_specs\k_flujo.spc
beautify C:\repo\risk\source\database\modules\flj\package_specs\k_flujo_util.spc
beautify C:\repo\risk\source\database\modules\msj\package_specs\k_mensajeria.spc
beautify C:\repo\risk\source\database\modules\msj\package_specs\k_servicio_msj.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_aplicacion.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_archivo.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_auditoria.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_autenticacion.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_autorizacion.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_cadena.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_clave.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_dato.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_dispositivo.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_dominio.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_error.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_html.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_importacion.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_json_util.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_lob_util.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_modulo.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_monitoreo.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_monitoreo_aut.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_operacion.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_reporte.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_reporte_gen.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_servicio.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_servicio_aut.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_servicio_gen.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_servicio_glo.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_sesion.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_significado.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_sistema.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_trabajo.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_usuario.spc
beautify C:\repo\risk\source\database\modules\risk\package_specs\k_util.spc
beautify C:\repo\risk\test\database\package_specs\test_gb_personas.spc
beautify C:\repo\risk\test\database\package_specs\test_k_aplicacion.spc
beautify C:\repo\risk\test\database\package_specs\test_k_archivo.spc
beautify C:\repo\risk\test\database\package_specs\test_k_auditoria.spc
beautify C:\repo\risk\test\database\package_specs\test_k_autenticacion.spc
beautify C:\repo\risk\test\database\package_specs\test_k_autorizacion.spc
beautify C:\repo\risk\test\database\package_specs\test_k_cadena.spc
beautify C:\repo\risk\test\database\package_specs\test_k_clave.spc
beautify C:\repo\risk\test\database\package_specs\test_k_dato.spc
beautify C:\repo\risk\test\database\package_specs\test_k_dispositivo.spc
beautify C:\repo\risk\test\database\package_specs\test_k_dominio.spc
beautify C:\repo\risk\test\database\package_specs\test_k_error.spc
beautify C:\repo\risk\test\database\package_specs\test_k_html.spc
beautify C:\repo\risk\test\database\package_specs\test_k_importacion.spc
beautify C:\repo\risk\test\database\package_specs\test_k_mensajeria.spc
beautify C:\repo\risk\test\database\package_specs\test_k_modulo.spc
beautify C:\repo\risk\test\database\package_specs\test_k_operacion.spc
beautify C:\repo\risk\test\database\package_specs\test_k_reporte.spc
beautify C:\repo\risk\test\database\package_specs\test_k_servicio.spc
beautify C:\repo\risk\test\database\package_specs\test_k_sesion.spc
beautify C:\repo\risk\test\database\package_specs\test_k_significado.spc
beautify C:\repo\risk\test\database\package_specs\test_k_sistema.spc
beautify C:\repo\risk\test\database\package_specs\test_k_trabajo.spc
beautify C:\repo\risk\test\database\package_specs\test_k_usuario.spc
beautify C:\repo\risk\test\database\package_specs\test_k_util.spc
beautify C:\repo\risk\test\database\package_specs\test_y_dato.spc
beautify C:\repo\risk\test\database\package_specs\test_y_respuesta.spc
beautify C:\repo\risk\source\database\modules\flj\package_bodies\k_flujo.bdy
beautify C:\repo\risk\source\database\modules\flj\package_bodies\k_flujo_util.bdy
beautify C:\repo\risk\source\database\modules\msj\package_bodies\k_mensajeria.bdy
beautify C:\repo\risk\source\database\modules\msj\package_bodies\k_servicio_msj.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_aplicacion.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_archivo.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_auditoria.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_autenticacion.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_autorizacion.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_cadena.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_clave.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_dato.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_dispositivo.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_dominio.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_error.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_html.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_importacion.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_json_util.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_lob_util.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_modulo.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_monitoreo.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_monitoreo_aut.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_operacion.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_reporte.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_reporte_gen.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_servicio.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_servicio_aut.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_servicio_gen.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_servicio_glo.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_sesion.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_significado.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_sistema.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_trabajo.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_usuario.bdy
beautify C:\repo\risk\source\database\modules\risk\package_bodies\k_util.bdy
beautify C:\repo\risk\test\database\package_bodies\test_gb_personas.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_aplicacion.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_archivo.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_auditoria.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_autenticacion.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_autorizacion.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_cadena.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_clave.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_dato.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_dispositivo.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_dominio.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_error.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_html.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_importacion.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_mensajeria.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_modulo.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_operacion.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_reporte.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_servicio.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_sesion.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_significado.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_sistema.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_trabajo.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_usuario.bdy
beautify C:\repo\risk\test\database\package_bodies\test_k_util.bdy
beautify C:\repo\risk\test\database\package_bodies\test_y_dato.bdy
beautify C:\repo\risk\test\database\package_bodies\test_y_respuesta.bdy
beautify C:\repo\risk\source\database\modules\flj\triggers\gb_flujo_instancia_pasos.trg
beautify C:\repo\risk\source\database\modules\flj\triggers\gb_roles.trg
beautify C:\repo\risk\source\database\modules\msj\triggers\gb_mensajes.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_archivos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_datos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_operaciones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_operacion_parametros.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_personas.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_reportes.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_servicios.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_sesiones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_trabajos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gb_usuarios.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gf_archivos.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gf_operaciones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gs_monitoreo_ejecuciones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gs_operaciones.trg
beautify C:\repo\risk\source\database\modules\risk\triggers\gs_operacion_logs.trg
beautify C:\repo\risk\source\database\modules\msj\type_specs\y_correo.tps
beautify C:\repo\risk\source\database\modules\msj\type_specs\y_mensaje.tps
beautify C:\repo\risk\source\database\modules\msj\type_specs\y_notificacion.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_archivo.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_archivos.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_barrio.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_cadenas.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_ciudad.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_dato.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_datos.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_departamento.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_dispositivo.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_error.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_objeto.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_objetos.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_pagina.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_pagina_parametros.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_pais.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_parametro.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_parametros.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_plantilla.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_respuesta.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_rol.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_sesion.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_significado.tps
beautify C:\repo\risk\source\database\modules\risk\type_specs\y_usuario.tps
beautify C:\repo\risk\source\database\modules\msj\type_bodies\y_correo.tpb
beautify C:\repo\risk\source\database\modules\msj\type_bodies\y_mensaje.tpb
beautify C:\repo\risk\source\database\modules\msj\type_bodies\y_notificacion.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_archivo.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_barrio.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_ciudad.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_dato.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_departamento.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_dispositivo.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_error.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_pagina.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_pagina_parametros.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_pais.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_parametro.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_plantilla.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_respuesta.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_rol.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_sesion.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_significado.tpb
beautify C:\repo\risk\source\database\modules\risk\type_bodies\y_usuario.tpb
exit application
