FROM container-registry.oracle.com/database/ords-developer:latest
EXPOSE 8181

ENV DB_NAME=$DB_NAME
ENV DB_SERVICE_NAME=$DB_SERVICE_NAME

ENV IGNORE_APEX=$IGNORE_APEX

USER oracle
COPY ./docker/frontend/conn_string.txt /opt/oracle/variables/
COPY ./source/frontend /usr/src/risk/source/
COPY ./docker/frontend/[0-9]*.sh /ords-entrypoint.d/