CREATE OR REPLACE FORCE VIEW T_DEPARTAMENTOS_V AS
SELECT ID_DEPARTAMENTO /*PK*/,
      NOMBRE,
      ID_PAIS /*FK*/,
      USUARIO_INSERCION,
      FECHA_INSERCION,
      USUARIO_MODIFICACION,
      FECHA_MODIFICACION
  FROM T_DEPARTAMENTOS 
  WITH READ ONLY
  /*
  This is the 1:1 view for the table T_DEPARTAMENTOS.
  - Generator:         OM_TAPIGEN
  - Generator version: 0.6.3
  - Generator action:  COMPILE_API
  - Generated at:      2026-03-15 15:14:01
  - Generated by:      JAVIER
  */;

