CREATE OR REPLACE FORCE VIEW T_DOCUMENTO_TIPOS_DML_V AS
SELECT ID_DOCUMENTO_TIPO /*PK*/,
      NOMBRE,
      DETALLE,
      ACTIVO,
      USUARIO_INSERCION,
      FECHA_INSERCION,
      USUARIO_MODIFICACION,
      FECHA_MODIFICACION
  FROM T_DOCUMENTO_TIPOS 
  /*
  This is the DML view for the table T_DOCUMENTO_TIPOS.
  - Generator:         OM_TAPIGEN
  - Generator version: 0.6.3
  - Generator action:  COMPILE_API
  - Generated at:      2026-03-15 15:14:03
  - Generated by:      JAVIER
  */;

