CREATE OR REPLACE FORCE VIEW T_PARAMETROS_V AS
SELECT ID_PARAMETRO /*PK*/,
      VALOR,
      USUARIO_INSERCION,
      FECHA_INSERCION,
      USUARIO_MODIFICACION,
      FECHA_MODIFICACION
  FROM T_PARAMETROS
  WITH READ ONLY
  /*
  This is the 1:1 view for the table T_PARAMETROS.
  - Generator:         OM_TAPIGEN
  - Generator version: 0.6.3
  - Generator action:  COMPILE_API
  - Generated at:      2026-03-10 22:59:50
  - Generated by:      JAVIER
  */;

