alter table T_IMPORTACION_PARAMETROS
  add constraint FK_IMP_PARAMETROS_IMPORTACIONES foreign key (ID_IMPORTACION)
  references T_IMPORTACIONES (ID_IMPORTACION);
alter table T_IMPORTACION_PARAMETROS
  add constraint FK_IMP_PARAMETROS_OPE_PARAMETROS foreign key (ID_IMPORTACION, NOMBRE, VERSION)
  references T_OPERACION_PARAMETROS (ID_OPERACION, NOMBRE, VERSION);
