CREATE OR REPLACE FORCE VIEW T_FLUJOS_DML_V AS
SELECT ID_FLUJO /*PK*/,
      NOMBRE,
      ACTIVO,
      DETALLE,
      VARIABLES_DEFECTO,
      USUARIO_INSERCION,
      FECHA_INSERCION,
      USUARIO_MODIFICACION,
      FECHA_MODIFICACION
  FROM T_FLUJOS
  /*
  This is the DML view for the table T_FLUJOS.
  - Generator:         OM_TAPIGEN
  - Generator version: 0.6.3
  - Generator action:  COMPILE_API
  - Generated at:      2026-03-10 22:59:56
  - Generated by:      JAVIER
  */;

